version: '3.4'

services:

  8080_web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    container_name: web
    ports:
      - "8080:8080"
    expose:
      - 8080

  8081_api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    container_name: api
    ports:
      - "8081:8081"
    expose:
      - 8081

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
