version: '3.4'

services:

  8080_web:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-web
    container_name: app-web
    ports:
      - "8080:8080"
    expose:
      - 8080

  8081_patient:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
      target: api-patient
    container_name: api-patient
    ports:
      - "8081:8081"
    expose:
      - 8081

  8082_notes:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
      target: api-notes
    container_name: api-notes
    ports:
      - "8082:8082"
    expose:
      - 8082

  db:
    build:
      context: .
      dockerfile: Dockerfile
      target: mysql-with-tables
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mediscreen
    ports:
      - "127.0.0.1:3308:3306" #exposed only in localhost

  8084-adminer:
    depends_on:
      - db
    image: adminer
    container_name: adminer
    ports:
      - "127.0.0.1:8084:8080" #exposed only in localhost

  mongo:
    image: mongo
    container_name: app-web
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword