version: '3.4'

volumes:
  mediscreen-mongodb:

networks:
  web:
  back:
  data:

services:

  # FRONT-END LAYER

  8080_web:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-web
    container_name: app-web
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - web
      - back

  # BACK-END / SERVICES LAYER

  8081_patient:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
      target: api-patient
    container_name: api-patient
    ports:
      - "8081:8081"
    networks:
      - back
      - data

  8082_notes:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
      target: api-notes
    container_name: api-notes
    ports:
      - "8082:8082"
    networks:
      - back
      - data

  8083_risk:
    build:
      context: .
      dockerfile: Dockerfile
      target: api-risk
    container_name: api-risk
    ports:
      - "8083:8083"
    networks:
      - back

  # DATABASES LAYER

  db:
    build:
      context: .
      dockerfile: Dockerfile
      target: mysql-with-tables
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mediscreen
    ports:
      - "3308:3306"
    networks:
      - data

  8084-admin-db:
    depends_on:
      - db
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "127.0.0.1:8084:8080" #ADMIN tool exposed only in localhost
    networks:
      - data

  mongo:
    image: mongo
    restart: always
    volumes:
      - mediscreen-mongodb:/var/lib/mediscreen-mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: patienthistory

  8085-admin-mongo:
    image: mongo-express
    depends_on:
      - mongo
    container_name: mongo-express
    restart: always
    ports:
      - "127.0.0.1:8085:8081" #ADMIN tool exposed only in localhost
    networks:
      - data
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_SERVER: mongo