version: '3.1'

services:

  8080_web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8080:8080"
    expose:
      - 8080

  8081_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8081:8081"
    expose:
      - 8081

